
# Basic Vagrant config (API version 2)
Vagrant.configure(2) do |config|
  # ... other stuff

  config.vm.provider "qemu" do |qe|
    qe.memory = "1G"
#    config.vm.box = "test-box"
    config.vm.box_url = "file:///Users/christian/devops/vagrant/vagrant_getting_started/test.box"
    config.vm.box_check_update = false
    qe.qemu_dir = "/usr/local/share/qemu"
  end
end
